### ISSUE TITLE
Casting Exception

### ISSUE THREAD

**Issue by habedi** [AngelQuirogaM/NiceJson#5]
Hi, 
Great library; I'm trying to parse a JSON array in Unity3D using SimpleJSON, when I call this in my code

```Csharp
...
JsonArray response = (JsonArray)JsonNode.ParseJsonString(MyJsonString);
...
```
I get this error(goLevel.cs is the script I'm calling JsonNode.ParseJsonString from):
```Bash
InvalidCastException: Cannot cast from source type to destination type.
goLevel+<WaitForRequest>c__Iterator0.MoveNext () (at Assets/_Scripts/goLevel.cs:99)
```
The content of MyJsonString is like:
```Json
"[{'platform': u'github', 'uri': u'https://github.com/habedi'}]\n"
```
Any suggestions to resolve this?
Thanks in advance.
Hassan

**Comment by AngelQuirogaM** [comment]
Hello, firstly this library is called "NiceJson", maybe you missunderstand it.

Going further this json is not in json format. Test it using jsonlint.com:

[{'platform': u'github', 'uri': u'https://github.com/habedi'}]

My solution is telling you to reformat your json string, because it's not in the regular format.
You're wellcome.

**Comment by habedi** [comment]
Hi, Sorry for the name,  I guess I meant NiceJSON but my hands wrote it down SimpleJSON!;).
Btw, 

[{'platform': u'github', 'uri': u'https://github.com/habedi'}]

is a valid JSON Array but the casting won't work; You used(contents of 'outPutString')

[{"name":"Ángel","age":27,"programmer":true,"glasses":null,"surname":"Surname"},{"name":"Manolo","age":54.4,"programmer":false,"glasses":["sunglases",3,null],"surname":"Surname"}]

in your example(here https://github.com/AngelQuirogaM/NiceJson) and it's in JSON Array format, It seems the example code is working but why it does not accept my JSON Array?

**Comment by AngelQuirogaM** [comment]
Maybe I'm worng but using strings starting with u char is not part of the json RFC:

u'github'

Check the RFC here : http://www.ietf.org/rfc/rfc4627.txt
And more simple here: http://www.json.org/

That's the difference I see in the code.

**Comment by habedi** [comment]
I don't think that's the case, u'string' is a Unicode(UTF-8 encoded in my case) string; When you don't use non-ASCII characters in your UTF-8 encoded string, it is completely compatible with ASCII. In other words
```Json
[{'platform': u'github', 'uri': u'https://github.com/habedi'}]
```

is equivalent to
```Json
[{'platform': 'github', 'uri': 'https://github.com/habedi'}]
```

when the string containing the JSON Array/JSON Object is encoded in UTF-8.

Another case is that [https://www.ietf.org/rfc/rfc4627.txt](https://www.ietf.org/rfc/rfc4627.txt) says
```Bash
JSON can represent four primitive types (strings, numbers, booleans,
   and null) and two structured types (objects and arrays).

   A string is a sequence of zero or more Unicode characters [UNICODE].
```

so  strings used in JSON Arrays/JSON Objects are made of Unicode characters.

My guess is NiceJSON does not support parsing JSON Arrays, but I am not sure.

**Comment by AngelQuirogaM** [comment]
I recommend you to take a look in this image:

http://www.json.org/string.gif

If you see in this image it's telling you exactly that there is no other char before the quote. I would like to know where is that code from to understand why they format that json in that horrible way.

Also my parser doesn't let to use other quotes than double ones ("), but you can change it in the code if you want.

And of course NiceJson supports JSON Arrays. Be pretty sure of  that 👍
