### ISSUE TITLE
Contains warning

### ISSUE THREAD

**Issue by mopsicus** [AngelQuirogaM/NiceJson#6]
How can I fix this warning?

` ''JsonObject.ContainsKey(string)' hides inherited member 'JsonNode.ContainsKey(string)'. Use the new keyword if hiding was intended. [Assembly-CSharp-firstpass]'
at: '768,21'
source: ''`

**Comment by AngelQuirogaM** [comment]
Im out now (writting from mobile) but this can be easily solved using the new reserved word on the method.

I will do it the next week.

I apologize for the inconvenienze

**Comment by mopsicus** [comment]
Cool, thanks

**Comment by AngelQuirogaM** [comment]
Sorry, I forgot to change it.
